extends: airbnb-base
plugins:
  - import
env:
  node: true
rules:
  strict: 0
  global-require: 0
  key-spacing:
    - error
    - align: value
  no-multi-spaces:
    - error
    - exceptions:
        VariableDeclarator: true
  import/no-extraneous-dependencies: 0
  no-param-reassign:
    - error
    - props: false
